### ISSUE TITLE
朋友 你的hook用的哪一个啊 ?

### ISSUE THREAD

**Issue by 23233** [Rosyrain/qyvx#1]

**Comment by Rosyrain** [comment]
企业微信官方hook，下载的官方提供的go语言xml版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月09日 00:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Rosyrain/qyvx] 朋友 你的hook用的哪一个啊 ? (Issue #1) |

**Comment by Rosyrain** [comment]
需要一个公网IP运行(不是公网的话考虑内网穿透)



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月09日 00:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Rosyrain/qyvx] 朋友 你的hook用的哪一个啊 ? (Issue #1) |

**Comment by Rosyrain** [comment]
参考文档
https://blog.csdn.net/weixin_45385457/article/details/132278442
[://developer.work.weixin.qq.com/devtool/introduce?id=10128](https://developer.work.weixin.qq.com/devtool/introduce?id=10128)
根据第一篇参考文档为自建应用配置可信ip,在此过程中需要使用到一个可以被访问到的ip(公网ip或内网穿透);其次根据第二篇参考文章选择合适的官方提供版本对信息进行解密并返回内容(本人使用go语言xml版本)
